language: android
dist: trusty
os: linux
jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_ABI=armeabi-v7a
    - EMULATOR_API_LEVEL=android-24

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-30.0.3
    - $EMULATOR_API_LEVEL
    - sys-img-${ANDROID_ABI}-${EMULATOR_API_LEVEL}

before_install:
  - yes | sdkmanager "platforms;android-24"
  - yes | sdkmanager "platforms;android-30"

script:
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - bash <(curl -s https://codecov.io/bash)